# Generated by Django 3.2.3 on 2021-07-07 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='rut',
        ),
        migrations.AddField(
            model_name='cliente',
            name='contrasena',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Contrasena'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(max_length=20, null=True, verbose_name='Dirección del proveedor'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='foto',
            field=models.ImageField(max_length=20, null=True, upload_to='', verbose_name='foto'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='moneda',
            field=models.CharField(max_length=20, null=True, verbose_name='Pesos o Dólares'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nombreCompleto',
            field=models.CharField(max_length=20, null=True, verbose_name='Nombre del proveedor'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='numeroId',
            field=models.CharField(max_length=9, null=True, primary_key=True, serialize=False, verbose_name='Numero de ID'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='pais',
            field=models.CharField(max_length=20, null=True, verbose_name='País del proveedor'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=20, null=True, verbose_name='Teléfono del proveedor'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Correo electrónico'),
        ),
    ]
